---

- name: AWS EC2 Sandbox Instance
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Launching EC2 Sandbox
      ec2:
        key_name: EC2KeyPair
        instance_type: t2.micro
        image: ami-083ebc5a49573896a
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 16
        wait: yes
        region: us-east-2
        group: launch-wizard-1 
        count: 1
        vpc_subnet_id: subnet-c2f031a9
        assign_public_ip: yes
      register: ec2  

    - name: Wait for SSH
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22 
        state: started 
      with_items: "{{ ec2.instances }}"